# Generated by Django 4.2.1 on 2023-06-07 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_from', models.TextField(max_length=255)),
                ('where_to', models.TextField(max_length=255)),
                ('date', models.DateField()),
                ('count_of_passengers', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('type_of_transport', models.TextField(max_length=255)),
                ('model_of_transport', models.TextField(max_length=255)),
                ('departure_times', models.TimeField()),
                ('duration', models.TimeField()),
                ('distance', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
