# Generated by Django 4.2.1 on 2023-06-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='free_place',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='count_of_passengers',
            field=models.IntegerField(),
        ),
    ]
