# Generated by Django 4.2.1 on 2023-05-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
