# Generated by Django 4.2.1 on 2023-05-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_is_super_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_super_admin',
            new_name='is_manager',
        ),
    ]
