# Generated by Django 4.2.1 on 2023-06-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reating', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='number',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
