# Generated by Django 4.2.1 on 2023-06-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reating', '0003_alter_rating_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='author',
            new_name='user',
        ),
    ]
