# Generated by Django 4.2.1 on 2023-06-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_remove_place_adres_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
    ]
